/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppValidationRouteImport } from './routes/app.validation'
import { Route as AppRoadmapRouteImport } from './routes/app.roadmap'
import { Route as AppResumeRouteImport } from './routes/app.resume'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppJourneyRouteImport } from './routes/app.journey'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppJourneyCreateRouteImport } from './routes/app.journey_.create'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppValidationRoute = AppValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyRoute = AppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyCreateRoute = AppJourneyCreateRouteImport.update({
  id: '/journey_/create',
  path: '/journey/create',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/validation': typeof AppValidationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/journey/create': typeof AppJourneyCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/validation': typeof AppValidationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/app/journey/create': typeof AppJourneyCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/journey': typeof AppJourneyRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/validation': typeof AppValidationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/journey_/create': typeof AppJourneyCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/insights'
    | '/app/journey'
    | '/app/profile'
    | '/app/resume'
    | '/app/roadmap'
    | '/app/validation'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/auth/'
    | '/app/journey/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/dashboard'
    | '/app/insights'
    | '/app/journey'
    | '/app/profile'
    | '/app/resume'
    | '/app/roadmap'
    | '/app/validation'
    | '/auth/login'
    | '/auth/signup'
    | '/app'
    | '/auth'
    | '/app/journey/create'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/insights'
    | '/app/journey'
    | '/app/profile'
    | '/app/resume'
    | '/app/roadmap'
    | '/app/validation'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/auth/'
    | '/app/journey_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/validation': {
      id: '/app/validation'
      path: '/validation'
      fullPath: '/app/validation'
      preLoaderRoute: typeof AppValidationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roadmap': {
      id: '/app/roadmap'
      path: '/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resume': {
      id: '/app/resume'
      path: '/resume'
      fullPath: '/app/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey': {
      id: '/app/journey'
      path: '/journey'
      fullPath: '/app/journey'
      preLoaderRoute: typeof AppJourneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey_/create': {
      id: '/app/journey_/create'
      path: '/journey/create'
      fullPath: '/app/journey/create'
      preLoaderRoute: typeof AppJourneyCreateRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppJourneyRoute: typeof AppJourneyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResumeRoute: typeof AppResumeRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppValidationRoute: typeof AppValidationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJourneyCreateRoute: typeof AppJourneyCreateRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppJourneyRoute: AppJourneyRoute,
  AppProfileRoute: AppProfileRoute,
  AppResumeRoute: AppResumeRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppValidationRoute: AppValidationRoute,
  AppIndexRoute: AppIndexRoute,
  AppJourneyCreateRoute: AppJourneyCreateRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
